import { NewsArticle } from "./definitions";
import { socket } from "./socket";

export function getDMRoom(a: string, b?: string) {
	if (typeof b === "undefined") {
		return `@me:${a}`;
	}

	const [u1, u2] = [a, b].sort();
	return `@me:${u1}:${u2}`;
}

export const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export function formatNumber(num?: number) {
	if (!num) return "0";
	if (num >= 1_000_000_000) return (num / 1_000_000_000).toFixed(1) + "B";
	if (num >= 1_000_000) return (num / 1_000_000).toFixed(1) + "M";
	if (num >= 1_000) return (num / 1_000).toFixed(1) + "K";
	return num.toString();
}

// generated by chatgpt (I am not good with regex)
export const normalizeMarkdown = (str: string) =>
	str
		.replace(/\r\n/g, "\n") // normalize line endings
		.split("\n") // split into lines
		.map((line) => line.trim()) // trim each line
		.filter((line) => line.length > 0) // remove empty lines
		.join("\n") // join lines back
		.trim(); // trim whole string

export function isServerRoom(roomId: string) {
	return !roomId.startsWith("@me:");
}

export function getLocalTimeString(date: string | Date, options?: Intl.DateTimeFormatOptions): string {
	const d = typeof date === "string" ? new Date(date) : date;
	return d.toLocaleTimeString([], options);
}

// generated by chatgpt
export function mapExternalArticle(article: any): NewsArticle {
	return {
		source: {
			id: article.source_id || null,
			name: Array.isArray(article.creator) ? article.creator[0] : article.creator || "Unknown",
		},
		author: Array.isArray(article.creator) ? article.creator[0] : article.creator || null,
		title: article.title,
		description: article.description || article.full_description || null,
		url: article.link,
		urlToImage: article.image_url || null,
		publishedAt: article.pubDate ? new Date(article.pubDate).toISOString() : new Date().toISOString(),
		content: article.content || null,
	};
}

export const getBackgroundColorByInitial = (char: string): string => {
	if (!char) return "bg-primary";

	const initial = char.toUpperCase();

	if ("ABC".includes(initial)) return "bg-rose-500";
	if ("DEF".includes(initial)) return "bg-amber-500";
	if ("GHI".includes(initial)) return "bg-emerald-500";
	if ("JKL".includes(initial)) return "bg-teal-500";
	if ("MNO".includes(initial)) return "bg-sky-500";
	if ("PQR".includes(initial)) return "bg-indigo-500";
	if ("STU".includes(initial)) return "bg-violet-500";
	if ("VWX".includes(initial)) return "bg-pink-500";
	if ("YZ".includes(initial)) return "bg-lime-500";

	return "bg-primary";
};

export function getBannerColor(char: string) {
	if (!char) return "bg-secondary";
	const initial = char.toUpperCase();

	if ("ABC".includes(initial)) return "bg-rose-600";
	if ("DEF".includes(initial)) return "bg-amber-600";
	if ("GHI".includes(initial)) return "bg-emerald-600";
	if ("JKL".includes(initial)) return "bg-teal-600";
	if ("MNO".includes(initial)) return "bg-sky-600";
	if ("PQR".includes(initial)) return "bg-indigo-600";
	if ("STU".includes(initial)) return "bg-violet-600";
	if ("VWX".includes(initial)) return "bg-pink-600";
	if ("YZ".includes(initial)) return "bg-lime-600";

	return "bg-secondary";
}

export function sendWithRetry(event: string, msg: any, retries = 3, delay = 2000) {
	return new Promise((resolve, reject) => {
		let attempts = 0;

		const attempt = () => {
			attempts++;
			// console.log(`Sending attempt ${attempts} for event "${event}"`);

			socket.timeout(5000).emit(event, msg, (err: any, response?: any) => {
				if (err) {
					// console.warn(`No ack from server for "${event}" (attempt ${attempts})`);

					if (attempts < retries) {
						setTimeout(attempt, delay); // retry after delay
					} else {
						reject(new Error(`Failed after ${retries} attempts`));
					}
				} else {
					// console.log(`Ack received for "${event}":`, response);
					resolve(response);
				}
			});
		};

		attempt();
	});
}

// export const examplePassage = `
// 			Space exploration has always fascinated humanity, but one of the most mysterious and intriguing objects in the universe is the black hole. A black hole is a region in space where the gravitational pull is so strong that nothing—not even light—can escape from it. Black holes are formed when massive stars collapse under their own gravity at the end of their life cycle. Despite being invisible, black holes reveal their presence by the effect they have on nearby stars and gas. The first-ever image of a black hole’s event horizon, captured in 2019 by the Event Horizon Telescope, confirmed many theoretical predictions about these cosmic phenomena. Black holes also challenge our understanding of physics, particularly the laws of relativity and quantum mechanics, making them a subject of intense scientific research.
// 		`;

export const examplePassages = {
	space: `
  Space exploration has fascinated humanity for centuries, pushing us to look beyond our home planet and wonder about the universe. Black holes are among the most mysterious cosmic objects, regions where gravity is so strong that nothing, not even light, can escape. They form when massive stars collapse under their own gravity at the end of their life cycle. Despite being invisible, their presence is revealed by how they affect nearby stars and gas clouds. The first-ever image of a black hole’s event horizon, captured in 2019, confirmed decades of theoretical predictions. Studying black holes challenges our understanding of physics and inspires new discoveries about the cosmos.
`,
	technology: `
  Artificial intelligence (AI) has transformed the way we live, work, and interact with technology. From virtual assistants and chatbots to self-driving cars and advanced data analytics, AI is becoming a central part of everyday life. At its core, AI uses algorithms and data to mimic aspects of human intelligence, allowing machines to learn from experience and improve over time. Ethical considerations, including privacy, bias, and accountability, are critical as AI becomes more powerful. The technology is also shaping industries, creating new jobs while transforming existing ones. As AI continues to evolve, understanding its potential and limitations is essential for society.
`,
	history: `
  The Industrial Revolution, beginning in the 18th century, marked a dramatic shift from agrarian societies to industrialized economies. Steam engines, mechanized looms, and factory production transformed how goods were made and how people lived. Urbanization accelerated as people moved to cities for work, creating new social and economic dynamics. The period also saw the rise of global trade, labor movements, and technological innovation. While the Industrial Revolution brought prosperity to some, it also led to harsh working conditions and environmental challenges. Its legacy continues to shape modern economies, technology, and society.
`,
	biology: `
  Photosynthesis is a remarkable process that sustains life on Earth by converting sunlight into chemical energy. Green plants, algae, and some bacteria use sunlight to transform carbon dioxide and water into glucose and oxygen, providing energy for themselves and for countless other organisms. This process not only fuels ecosystems but also maintains the planet’s oxygen levels and carbon balance. The efficiency of photosynthesis has inspired scientific research into renewable energy and sustainable agriculture. Understanding photosynthesis helps us appreciate the delicate interconnectedness of life. It is one of nature’s most fundamental and awe-inspiring processes.
`,
	literature: `
  William Shakespeare is considered one of the greatest writers in the English language, whose works continue to captivate audiences centuries after they were written. His plays and sonnets explore timeless themes like love, ambition, power, and human frailty. Works such as "Hamlet," "Macbeth," and "Romeo and Juliet" have influenced countless writers, filmmakers, and artists around the world. Shakespeare’s mastery of language, character development, and storytelling set a benchmark for literary excellence. His works are still performed and studied widely, revealing the depth of human emotion and experience. Shakespeare reminds us that literature can transcend time, culture, and society.
`,
	physics: `
  Quantum mechanics is a branch of physics that explores the behavior of matter and energy at the smallest scales. It reveals phenomena that seem impossible under classical physics, such as particles existing in multiple states at once and instant connections between distant particles. These discoveries challenge our intuition and deepen our understanding of the universe. Quantum mechanics is essential for technologies like semiconductors, lasers, and quantum computers. Scientists continue to probe its mysteries, seeking to reconcile it with general relativity. The field reshapes our conception of reality and inspires profound questions about the nature of existence.
`,
	geography: `
  The Amazon Rainforest is the largest tropical rainforest in the world, spanning multiple countries in South America. Its vast expanse houses millions of plant and animal species, many of which are still undiscovered. The rainforest plays a critical role in regulating Earth’s climate by absorbing carbon dioxide and producing oxygen. Indigenous communities have lived sustainably in the Amazon for centuries, relying on its resources for survival. However, deforestation, mining, and climate change threaten its delicate ecosystems. Protecting the Amazon is crucial for biodiversity, climate stability, and the health of the planet.
`,
	medicine: `
  Vaccines are one of the most important tools in modern medicine, preventing countless diseases and saving millions of lives. They work by stimulating the immune system to recognize and fight harmful pathogens, building immunity without causing illness. Vaccination programs have eradicated diseases like smallpox and significantly reduced others, including polio and measles. Modern research continues to develop vaccines for emerging threats, such as COVID-19. Vaccines also highlight the importance of public health, education, and global cooperation. They are a testament to the power of science to protect and improve human life.
`,
	art: `
  Impressionism emerged in 19th-century France as a revolutionary approach to painting, challenging traditional techniques and perspectives. Artists like Claude Monet, Pierre-Auguste Renoir, and Edgar Degas focused on capturing light, color, and fleeting moments rather than precise details. They painted landscapes, urban scenes, and everyday life with loose, expressive brushwork, emphasizing the feeling of a moment over realism. The movement influenced not only visual art but also literature, music, and culture. Impressionism encouraged experimentation and individuality in creative expression. Its legacy continues to inspire artists and audiences around the world.
`,
	climate: `
  Climate change refers to long-term shifts in temperature, precipitation, and weather patterns on Earth, largely driven by human activities. Burning fossil fuels, deforestation, and industrial processes release greenhouse gases, trapping heat in the atmosphere. The consequences include rising sea levels, extreme weather events, melting glaciers, and threats to biodiversity. Addressing climate change requires global cooperation, sustainable energy solutions, and environmental stewardship. Scientists, policymakers, and communities are working together to mitigate its impact and adapt to changes. Understanding climate change is essential for protecting the planet and ensuring a sustainable future.
`,
};
