import z from "zod";
import { NewsArticle, Room, User } from "./definitions";
import { socket } from "./socket";
import { BsChatDotsFill } from "react-icons/bs";
import { RiCompassDiscoverFill } from "react-icons/ri";
import CreateServerFormDialog from "../ui/form/CreateServerForm";

export function getDMRoom(a: string, b?: string) {
	if (typeof b === "undefined") {
		return `@me:${a}`;
	}

	const [u1, u2] = [a, b].sort();
	return `@me:${u1}:${u2}`;
}

export const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));

export function formatNumber(num?: number) {
	if (!num) return "0";
	if (num >= 1_000_000_000) return (num / 1_000_000_000).toFixed(1) + "B";
	if (num >= 1_000_000) return (num / 1_000_000).toFixed(1) + "M";
	if (num >= 1_000) return (num / 1_000).toFixed(1) + "K";
	return num.toString();
}

// generated by chatgpt (I am not good with regex)
export const normalizeMarkdown = (str: string) =>
	str
		.replace(/\r\n/g, "\n") // normalize line endings
		.split("\n") // split into lines
		.map((line) => line.trim()) // trim each line
		.filter((line) => line.length > 0) // remove empty lines
		.join("\n") // join lines back
		.trim(); // trim whole string

export function getLocalTimeString(date?: string | Date, options?: Intl.DateTimeFormatOptions): string {
	if (!date) {
		console.log("DATE IS NOT TRUE ");
		return "";
	} // handle undefined/null
	const d = typeof date === "string" ? new Date(date) : date;
	if (isNaN(d.getTime())) {
		console.log("DATE IS NOT NAN");
		return "";
	} // invalid date check
	return d.toLocaleTimeString([], options);
}

// generated by chatgpt
export function mapExternalArticle(article: any): NewsArticle {
	return {
		source: {
			id: article.source_id || null,
			name: Array.isArray(article.creator) ? article.creator[0] : article.creator || "Unknown",
		},
		author: Array.isArray(article.creator) ? article.creator[0] : article.creator || null,
		title: article.title,
		description: article.description || article.full_description || null,
		url: article.link,
		urlToImage: article.image_url || null,
		publishedAt: article.pubDate ? new Date(article.pubDate).toISOString() : new Date().toISOString(),
		content: article.content || null,
	};
}

export const getBackgroundColorByInitial = (char: string): string => {
	if (!char) return "bg-primary";

	const initial = char.toUpperCase();

	if ("ABC".includes(initial)) return "bg-rose-500";
	if ("DEF".includes(initial)) return "bg-amber-500";
	if ("GHI".includes(initial)) return "bg-emerald-500";
	if ("JKL".includes(initial)) return "bg-teal-500";
	if ("MNO".includes(initial)) return "bg-sky-500";
	if ("PQR".includes(initial)) return "bg-indigo-500";
	if ("STU".includes(initial)) return "bg-violet-500";
	if ("VWX".includes(initial)) return "bg-pink-500";
	if ("YZ".includes(initial)) return "bg-lime-500";

	return "bg-primary";
};

export function getBannerColor(char: string) {
	if (!char) return "bg-secondary";
	const initial = char.toUpperCase();

	if ("ABC".includes(initial)) return "bg-rose-600";
	if ("DEF".includes(initial)) return "bg-amber-600";
	if ("GHI".includes(initial)) return "bg-emerald-600";
	if ("JKL".includes(initial)) return "bg-teal-600";
	if ("MNO".includes(initial)) return "bg-sky-600";
	if ("PQR".includes(initial)) return "bg-indigo-600";
	if ("STU".includes(initial)) return "bg-violet-600";
	if ("VWX".includes(initial)) return "bg-pink-600";
	if ("YZ".includes(initial)) return "bg-lime-600";

	return "bg-secondary";
}

export function isRoom(input: any): input is Room {
	return input && typeof input === "object" && typeof input.owner_id === "string" && typeof input.type === "string";
}

export function isUser(input: any): input is User {
	return (
		input && typeof input === "object" && typeof input.username === "string" && typeof input.displayName === "string"
	);
}

// export function sendWithRetry(event: string, msg: any, retries = 3, delay = 2000) {
// 	return new Promise((resolve, reject) => {
// 		let attempts = 0;

// 		const attempt = () => {
// 			attempts++;
// 			// console.log(`Sending attempt ${attempts} for event "${event}"`);

// 			socket.timeout(5000).emit(event, msg, (err: any, response?: any) => {
// 				if (err) {
// 					// console.warn(`No ack from server for "${event}" (attempt ${attempts})`);

// 					if (attempts < retries) {
// 						setTimeout(attempt, delay); // retry after delay
// 					} else {
// 						reject(new Error(`Failed after ${retries} attempts`));
// 					}
// 				} else {
// 					// console.log(`Ack received for "${event}":`, response);
// 					resolve(response);
// 				}
// 			});
// 		};

// 		attempt();
// 	});
// }

export const NavigationSections = [
	{
		name: "Direct Messages",
		href: "/",
		icon: BsChatDotsFill,
		description: "Direct Messages",
	},
	{
		name: "Add New",
		href: null,
		icon: CreateServerFormDialog,
		description: "Add/Join a server",
	},
	{
		name: "Discover",
		href: "/discover",
		icon: RiCompassDiscoverFill,
		description: "Discover Communities",
	},
	// {
	// 	name: "Star",
	// 	href: "https://github.com/calvintaw/discord_clone",
	// 	icon: FaStar,
	// 	description: "Star my repo ;)",
	// 	external: true,
	// },
];

// const regex = /^ (?:(?!www\.)[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,} /g;
// const regex =
// 	// /^(?!:\/\/)(?!.{256})(?!.*\.{2})[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)*\.[a-z]{2,63}$/gi;



export const SHORT_URL_REGEX =
		/^(?!www\.)(?!.*\.\.)(?!.*-\.)(?!.*\.-)(?!.*\.$)[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)*\.[a-z]{2,63}$/i;

// const regex = /^(?:(?!www\.)[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$/g;
// const regex = /(?<![a-zA-Z0-9-])(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}(?![a-zA-Z0-9-])/g;

export const URL_REGEX_ADVANCED =
	/\b((?:[a-z][\w-]+:(?:\/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}\/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))/gi;

export function includeLinks(text: string) {
	const matches1 = text.match(SHORT_URL_REGEX);
	const matches2 = text.match(URL_REGEX_ADVANCED);

	return !!matches1?.length || !!matches2?.length;
}

const testPassage = `omg bro look at this 😂 https://youtu.be/dQw4w9WgXcQ??t=43 and ALSO check this weird one http://192.168.1.15:3000/test?debug=true lol. btw I found another link→www.example.com/page#section-2 but it only works if u add https so see if your code handles that. oh and watch out for this: https://google.com,...yeah the comma shouldn't be part of the link. same for this one: https://openai.com/) where the ) is just punctuation. 

last one: "http://lol.test" inside quotes… make sure your regex doesn’t break it 😭
`;


const testText = `
Check out these links:
1. http://example.com
2. https://example.com
3. http://example.com/
4. https://example.com/path
5. https://example.com/path/
6. https://example.com/path?ref=123
7. https://www.example.com/path?ref=123
8. https://example.com/path#section
9. www.test-site.org
10. test-site.org
11. https://sub.domain.com
12. http://sub.domain.com/page
13. https://sub.domain.com/page?query=value
14. https://xn--fsq.com (human-readable punycode: 🐱.com)
15. https://example.co.uk/path
16. example.co.uk
17. http://example.co.uk/path?utm_source=newsletter
18. https://example.com/path/to/resource
19. https://example.com/path/to/resource/  // trailing slash
20. https://example.com/path/to/resource?foo=bar
21. https://example.com:8080/path
22. https://example.com/path(with-parentheses)
23. https://example.com/path%20with%20spaces
24. https://example.com/path-with-dash
25. http://localhost:3000/test
26. http://127.0.0.1:8000/page
`;
